apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-apache-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: pre-sync-job
        image: busybox
        command: ['sh', '-c', 'echo PreSync Job running before Apache deployment']
      restartPolicy: Never
